version: '3.10'

services:
  email:
    image: lindsey98/email:latest
    build: ./
    ports:
      - 8000:8000
    command: ["--email_dir=./test_emails/2015"]  # Example to override CMD
    environment:
      - IDENTITY_MODEL_CHECKPOINT=./checkpoints/identity-model
      - MATCHING_MODEL_CHECKPOINT=./checkpoints/characterbert-typos-st
      - REF_IDENTITY_REPS=./checkpoints/company_database_reps.npy
      - REF_IDENTITY_NAMES=./checkpoints/company_database_names.npy
      - REF_IDENTITY_MAP=./checkpoints/company_database_knowphish.json
      - REF_RELATION_REPS=./checkpoints/internal_relation_reps.npy
      - REF_RELATION_NAMES=./checkpoints/internal_relation_names.npy
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890