# .github/workflows/docs.yml
name: Build and Deploy Documentation on Multiple OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cloning the repository into the current directory..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/lindsey98/PhishEmail.git .

      # Step 2: Install Dependencies and Python
      - name: Install Dependencies and Python
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Installing Python 3.8 on Windows..."
            choco install python --version 3.8 -y
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "Installing Python 3.8 on macOS..."
              brew install pyenv
              pyenv install 3.8.17  # Use the latest available patch version of Python 3.8
              pyenv global 3.8.17
          else
            echo "Installing Python 3.8 on Linux..."
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa -y
            sudo apt-get update
            sudo apt-get install -y python3.8 python3.8-venv python3.8-dev
          fi

      # Step 3: Set Up Python Virtual Environment
      - name: Set Up Python Virtual Environment
        run: |
          echo "Setting up Python 3.8 virtual environment..."
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            python -m venv venv
            venv\Scripts\activate
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            python3 -m venv venv
            source venv/bin/activate
          else
            python3.8 -m venv venv
            source venv/bin/activate
          fi
          python -m pip install --upgrade pip

      # Step 4: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          echo "Installing Python dependencies..."
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            venv\Scripts\activate
          else
            source venv/bin/activate
          fi
          pip install --no-input -r requirements.txt
          pip install --no-input sphinx
          sphinx-quickstart docs
          pip install --no-input gdown

      # Step 5: Install System Dependencies
      - name: Install System Dependencies
        run: |
          echo "Installing system dependencies..."
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install wkhtmltopdf --yes
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install poppler
            brew install wkhtmltopdf
          else
            sudo apt-get update
            sudo apt-get install -y poppler-utils wkhtmltopdf
          fi

      # Step 6: Download and Setup Checkpoints
      - name: Download and Setup Checkpoints
        run: |
          echo "Downloading checkpoints..."
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            venv\Scripts\activate
            $env:FILE_ID="1OqrhuKMOq8kjkKuU3jtPo9a-jA1zsJj8"
            $env:FILE_NAME="checkpoints.zip"
            gdown --id $env:FILE_ID -O $env:FILE_NAME
            Expand-Archive -Path $env:FILE_NAME -DestinationPath checkpoints
            cd checkpoints
            if (Test-Path "./checkpoints") {
              Move-Item -Path "./checkpoints/*" -Destination "./" -Force
              Remove-Item -Recurse -Force "./checkpoints"
            }
            cd ..
          else
            source venv/bin/activate
            FILE_ID="1OqrhuKMOq8kjkKuU3jtPo9a-jA1zsJj8"
            FILE_NAME="checkpoints.zip"
            gdown --id "$FILE_ID" -O "$FILE_NAME"
            unzip "$FILE_NAME" -d checkpoints/
            cd checkpoints
            if [ -d "checkpoints" ]; then
              mv checkpoints/* .
              rmdir checkpoints
            fi
            cd ..
          fi

     # Step 7: Build Documentation
      - name: Build Documentation
        run: |
          echo "Building documentation..."
          cd docs
          make html


      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to GitHub Pages..."
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cd docs\_build\html
          else
            cd docs/_build/html
          fi
          
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy documentation"
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/lindsey98/PhishEmail.git master:gh-pages